# .streamlit/secrets.toml

[auth0]
domain = "dev-xwbn3q4g6grwjm0c.us.auth0.com"
client_id = "hy9gWZRHCutUcivKe7YwDOJOTWR3kWaZ"
client_secret = "7W9jODsEGlj_gknBV5AE-0axnuZvgDJswdQU-jChBMrvIJAHq8cNiBjcHAz3zCMS"
# CORRECT
audience = "https://dev-xwbn3q4g6grwjm0c.us.auth0.com/api/v2/"
